import re, json
# Phonetic respellings applied at render time (both voices). V5: +47 names for the new running order.
# Set APPLY_RESPELLING = False in render_kokoro.py / render_edge.py to hear native pronunciation instead.
PRONUNCIATION = json.loads(r'''{"Pietro da Cortona": "Pee-ay-tro da Kor-toh-na", "Cristofano Allori": "Krees-toh-fah-no Al-loh-ree", "Andrea del Sarto": "An-dray-a del Sar-toh", "Fra Bartolomeo": "Fra Bar-toh-loh-may-oh", "Filippo Lippi": "Fee-leep-po Lip-pee", "Giambologna": "Jam-bo-loh-nya", "Macchiaioli": "Mah-kya-yoh-lee", "Volterrano": "Vol-teh-rah-no", "Ammannati": "Am-mah-nah-tee", "Giorgione": "Jor-joh-nay", "Gabbiani": "Gab-bee-ah-nee", "Pontormo": "Pon-tor-mo", "Cristofano": "Krees-toh-fah-no", "Ghirlandaio": "Gheer-lan-dye-oh", "Gentileschi": "Jen-tee-less-kee", "Buontalenti": "Bwon-ta-len-tee", "Caravaggio": "Kah-rah-vah-jo", "Masaccio": "Mah-zah-cho", "Vasari": "Vah-zah-ree", "Cortona": "Kor-toh-na", "Fattori": "Fat-toh-ree", "Cosimo": "Kaw-zee-mo", "Medici": "Med-ee-chee", "Boboli": "Boh-boh-lee", "Giotto": "Jot-toh", "Allori": "Al-loh-ree", "Lippi": "Lip-pee", "Tacca": "Tahk-ka", "Ussi": "Oos-see", "Agnolo": "Ahn-yoh-lo", "Doni": "Doh-nee", "Acciaioli": "Ah-chah-yoh-lee", "Cerretieri Visdomini": "Cher-reh-tyeh-ree Veez-doh-mee-nee", "Bezzuoli": "Bet-tswoh-lee", "Ademollo": "Ah-deh-mol-lo", "Fortini": "For-tee-nee", "Gryaznov": "Gryahz-nov", "Bacchino": "Bahk-kee-no", "Viottolone": "Vyot-toh-loh-nay", "Isolotto": "Ee-zoh-lot-toh", "Limonaia": "Lee-moh-nye-ya", "Annalena": "Ahn-na-lay-na", "Kaffeehaus": "Kaff-ay-house", "Impannata": "Eem-pahn-nah-ta", "Seggiola": "Sej-joh-la", "Baldacchino": "Bal-dahk-kee-no", "Granduca": "Gran-doo-ka", "Gravida": "Grah-vee-da", "Velata": "Veh-lah-ta", "Giove": "Joh-vay", "Saturno": "Sah-toor-no", "Venere": "Veh-neh-ray", "Nicchie": "Neek-kyeh", "Iliade": "Ee-lee-ah-deh", "Stufa": "Stoo-fa", "Educazione": "Eh-doo-kah-tsyoh-nay", "Staffato": "Staf-fah-toh", "Macchia": "Mahk-kya", "Chirico": "Kee-ree-ko", "Meridiana": "Meh-ree-dyah-na", "Palazzina": "Pah-lat-tsee-na", "Oltrarno": "Ol-trar-no", "Bargello": "Bar-jel-lo", "Ghiberti": "Ghee-bair-tee", "Sabatelli": "Sah-ba-tel-lee", "Passerini": "Pas-seh-ree-nee", "Baciocchi": "Bah-chok-kee", "Poccetti": "Pot-chet-tee", "Cacialli": "Kah-chahl-lee", "Mazzafirra": "Mat-tsa-feer-ra", "Sustermans": "Soos-ter-mahns", "Brunelleschi": "Broo-nel-less-kee", "Bandinelli": "Ban-dee-nel-lee", "Accademia": "Ak-ka-day-mya", "Opificio delle Pietre Dure": "Oh-pee-fee-cho del-leh Pyeh-treh Doo-reh"}''')

def apply_respelling(text, enable=True):
    if not enable:
        return text
    for name in sorted(PRONUNCIATION, key=len, reverse=True):
        text = re.sub(r'\b' + re.escape(name) + r'\b', PRONUNCIATION[name], text)
    return text
